[Fix] 'Board' 전체 조회 및 태그로 조회 날짜별로 그룹화
umc-bonheur/bonheur-server pull request #106
Opened 2023-01-27 02:37 UTC by m2nja201

## 개요
#104 ``[Fix] 전체 조회 및 해시 태그로 조회 날짜로 그룹화``

## 작업 사항
- [x] BoardService에 날짜별 그룹화 로직 추가 : getBoardsGroups
- [x] BoardController반환 값 getBoardsGroups 사용하여 GetBoardsGroupsResponse로 변경

2023-01-27 08:23 UTC, Torres-09 requested changes
고생했습니다.

2023-01-27 08:23 UTC, Torres-09 commented on src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
> +        return new GetBoardsResponse(contents, boardTags, image, createdAtDate, createdAtTime);
null을 구분하여 생성자를 만들어서 넣어줄 필요가 없습니다.
only use return new GetBoardsResponse(contents, boardTags, image, createdAtDate, createdAtTime);

2023-01-28 14:29 UTC, m2nja201 commented on src/main/java/com/bonheur/domain/board/model/dto/GetBoardsResponse.java
> +        return new GetBoardsResponse(contents, boardTags, image, createdAtDate, createdAtTime);
그러네유 고쳤습니다

2023-01-29 04:08 UTC, zer0silver approved these changes
수고하셨습니다 👍

2023-01-29 04:11 UTC, zer0silver commented
수고하셨습니다 👍

2023-01-29 06:25 UTC, Torres-09 approved these changes
고생했습니다.

2023-01-29 06:25 UTC, merged